# Generated by Django 5.2.4 on 2025-07-21 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hr_number", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=8,
                    ),
                ),
            ],
        ),
    ]
