# Generated by Django 5.2.4 on 2025-07-21 09:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["hr_number"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp when the account was created",
                verbose_name="Account Created At",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                help_text="Official job title",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hr_number",
            field=models.CharField(
                help_text="Unique HR identifier",
                max_length=20,
                unique=True,
                verbose_name="HR Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="Employee full name", max_length=100, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="Password (should be stored securely)",
                max_length=128,
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="User account status",
                max_length=8,
                verbose_name="Account Status",
            ),
        ),
    ]
