# Generated by Django 5.2.4 on 2025-07-23 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_options_alter_user_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NFDQueue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "assigned_id",
                    models.CharField(
                        help_text="Unique ID assigned during scheduling",
                        max_length=50,
                        verbose_name="Assigned ID",
                    ),
                ),
                (
                    "assigned_month",
                    models.DateField(
                        help_text="Month this employee is expected for duty",
                        verbose_name="Assigned Month",
                    ),
                ),
                (
                    "duty_type",
                    models.CharField(
                        choices=[("weekday", "Weekday"), ("weekend", "Weekend")],
                        help_text="Type of duty (Weekday or Weekend)",
                        max_length=10,
                        verbose_name="Duty Type",
                    ),
                ),
                (
                    "added_to_queue_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When employee was added to duty queue",
                        verbose_name="Added To Queue",
                    ),
                ),
                (
                    "removed_from_queue_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When employee was removed (assigned/skipped)",
                        null=True,
                        verbose_name="Removed From Queue",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("assigned", "Assigned"),
                            ("skipped", "Skipped"),
                        ],
                        default="active",
                        help_text="Current queue status of this duty entry",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee scheduled for next duty",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nfd_entries",
                        to="core.user",
                        verbose_name="Employee",
                    ),
                ),
            ],
            options={
                "verbose_name": "Next For Duty",
                "verbose_name_plural": "NFD Queue",
                "ordering": ["assigned_month", "added_to_queue_at"],
            },
        ),
    ]
