# Generated by Django 5.2.4 on 2025-07-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_nfdqueue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the national or religious event",
                        max_length=100,
                        verbose_name="Event Name",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Start date of the event (for lunar, this is estimated)",
                        verbose_name="Start Date",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Leave blank if single-day event",
                        null=True,
                        verbose_name="End Date",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("lunar", "Lunar")],
                        max_length=10,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, the event will be ignored this year",
                        verbose_name="Is Active This Year?",
                    ),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="EventDutyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("duty_date", models.DateField()),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.user"
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Event Duty Record",
                "verbose_name_plural": "Event Duty Records",
                "unique_together": {("employee", "duty_date")},
            },
        ),
    ]
