# Generated by Django 5.2.4 on 2025-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_event_eventdutyrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_weekend",
            field=models.BooleanField(
                default=False,
                help_text="Mark as Yes if this event falls on a weekend",
                verbose_name="Is Weekend?",
            ),
        ),
    ]
