# Generated by Django 5.2.4 on 2025-07-26 20:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_event_is_weekend"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("suprident", "Suprident"), ("employee", "Employee")],
                default="employee",
                help_text="Role of the user (Suprident or Employee)",
                max_length=10,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Timestamp when the account was created",
                verbose_name="Account Created At",
            ),
        ),
    ]
