# Generated by Django 5.2.4 on 2025-07-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_role_alter_user_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdutyrecord",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duty_records",
                to="core.event",
            ),
        ),
    ]
