# Generated by Django 5.2.4 on 2025-07-27 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_eventdutyrecord_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventdutyrecord",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.event",
            ),
        ),
    ]
