# Generated by Django 5.2.4 on 2025-07-30 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_email_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                editable=False,
                help_text="Timestamp when the account was created",
                verbose_name="Account Created At",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="designation",
            field=models.CharField(
                help_text="Official job title",
                max_length=100,
                verbose_name="Designation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="hr_number",
            field=models.CharField(
                help_text="Unique HR identifier",
                max_length=20,
                unique=True,
                verbose_name="HR Number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(
                help_text="Employee full name", max_length=100, verbose_name="Full Name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                help_text="Password (should be stored securely)",
                max_length=128,
                verbose_name="Password",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("suprident", "Superintendent")],
                default="employee",
                help_text="Whether user is Superintendent or Employee",
                max_length=20,
                verbose_name="User Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                help_text="User account status",
                max_length=8,
                verbose_name="Account Status",
            ),
        ),
    ]
