# Generated by Django 5.2.4 on 2025-08-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_user_email_remove_user_groups_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nfdqueue",
            options={
                "ordering": ["assigned_month", "duty_date"],
                "verbose_name": "Next For Duty",
                "verbose_name_plural": "NFD Queue",
            },
        ),
        migrations.RemoveField(
            model_name="nfdqueue",
            name="status",
        ),
        migrations.AddField(
            model_name="nfdqueue",
            name="duty_date",
            field=models.DateField(
                blank=True,
                help_text="Exact duty date for this NFD entry",
                null=True,
                verbose_name="Duty Date",
            ),
        ),
    ]
